# Assignment
Take the Restaurant dataset given in google classroom


# Question 1
Prepare the data for modelling, This will include
- Converting to lowercase
- Removing stopwords
- Lemmatization
- Stemming
- Removing numbers 

### Brownie points if you can do it all in 1 function

# Question 2
Once the data has been cleaned :-
- Divide the data intro train and test parts
- Convert the training and text text into vectors 
- Convert the labels intro numbers(encoding)

Overall, you should end up with 4 varaibles 
- Xtrain
- Xtest
- Ytrain
- Ytest

You can name these whatever you want, upto you. But i am looking for these 4 variables ready to go for modelling

------------

![](https://media.tenor.com/d8fG2J6pkAUAAAAC/friends-chandler.gif)

# A hint
The file is stores as a ```tsv```.

You can load a ```tsv``` file with ```pd.read_csv``` while passing the seperator or ```sep``` argument as ```\t```.

This tells pandas that the file is seperated by tab's instead of comma's

In [2]:
import pandas

In [3]:
data = pandas.read_csv('/Users/meghnarana/Downloads/datasets/Restaurant_Reviews.tsv',sep='\t')

In [4]:
data

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [5]:
import nltk

from nltk.tokenize import word_tokenize

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

from nltk.corpus import stopwords

from nltk.stem.snowball import SnowballStemmer
sn_stemmer=SnowballStemmer("english")

In [24]:
def datacleaning(data):

    x = data.lower()
    y = word_tokenize(x)
    temp = []
    for i in y:
        if i.isdigit():
            pass
        else:
            temp.append(i)
    rem = ' '.join(temp)
    
    y1 = word_tokenize(rem)
    temp1  = []
    for i in y1:
        if i in stopwords.words("english"):
            pass
        else:
            temp1.append(i)
    rem1 = ' '.join(temp1)
    
    y2 = word_tokenize(rem1)
    temp2 = []
    for i in y2:
        temp2.append(lemmatizer.lemmatize(i))
        rem2 = ' '.join(temp2)
    
    y3 = word_tokenize(rem2)
    temp3 = []
    for i in y3:
        temp3.append(sn_stemmer.stem(i))
        rem3 = ' '.join(temp3) 
     
    return rem3

In [26]:
data['Cleaned'] = data['Review'].apply(datacleaning)

In [27]:
data

Review  Liked  \
0                             Wow... Loved this place.      1   
1                                   Crust is not good.      0   
2            Not tasty and the texture was just nasty.      0   
3    Stopped by during the late May bank holiday of...      1   
4    The selection on the menu was great and so wer...      1   
..                                                 ...    ...   
995  I think food should have flavor and texture an...      0   
996                           Appetite instantly gone.      0   
997  Overall I was not impressed and would not go b...      0   
998  The whole experience was underwhelming, and I ...      0   
999  Then, as if I hadn't wasted enough of my life ...      0   

                                               Cleaned  
0                                 wow ... love place .  
1                                         crust good .  
2                                 tasti textur nasti .  
3    stop late may bank holiday rick steve recommen...  
4                            select menu great price .  
..                                                 ...  
995                    think food flavor textur lack .  
996                             appetit instant gone .  
997                     overal impress would go back .  
998  whole experi underwhelm , think ll go ninja su...  
999  , n't wast enough life , pour salt wound draw ...  

[1000 rows x 3 columns]

In [29]:
from sklearn.model_selection import train_test_split

In [31]:
xdata = data['Cleaned']

In [32]:
ydata = data['Liked']

In [33]:
xtrain, xtest, ytrain, ytest = train_test_split(xdata, ydata, test_size=0.2)

In [34]:
xtrain

63                                  'd definit go back .
488                attach gas station , rare good sign .
757                                    great place eat !
930                     food par denni 's , say , good .
40                                 shrimp tender moist .
                             ...                        
950                                      n't busi know .
23                   could care le ... interior beauti .
752    level spici perfect , spice n't over-whelm soup .
959    reason eat would fill night bing drink get car...
104                                  one better buffet .
Name: Cleaned, Length: 800, dtype: object

In [35]:
xtest

354                                         delici ! ! !
401           overal , disappoint qualiti food bouchon .
265                                     plus , 's buck .
168                                 ve never treat bad .
202                                 warm beer n't help .
                             ...                        
814                                         love place .
479                                               love !
951    tabl outsid also dirti lot time worker alway f...
461    vanilla ice cream creami smooth profiterol ( c...
712                                            thumb ! !
Name: Cleaned, Length: 200, dtype: object

In [36]:
ytrain

63     1
488    0
757    1
930    0
40     1
      ..
950    0
23     1
752    1
959    0
104    1
Name: Liked, Length: 800, dtype: int64

In [37]:
ytest

354    1
401    0
265    1
168    0
202    0
      ..
814    1
479    1
951    0
461    1
712    1
Name: Liked, Length: 200, dtype: int64

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

In [40]:
vectorizer = CountVectorizer()

In [42]:
vectorizer.fit(xtrain)

CountVectorizer()

In [45]:
xtrain_vector = vectorizer.transform(xtrain)

In [47]:
xtrain_vector

<800x1380 sparse matrix of type '<class 'numpy.int64'>'
	with 4326 stored elements in Compressed Sparse Row format>

In [48]:
xtest_vector = vectorizer.transform(xtest)

In [49]:
xtest_vector

<200x1380 sparse matrix of type '<class 'numpy.int64'>'
	with 906 stored elements in Compressed Sparse Row format>

In [50]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [59]:
le.classes_

array([0, 1])

In [58]:
le.fit(ytrain)

LabelEncoder()

In [57]:
ytrain_vector = le.transform(ytrain)

In [62]:
ytrain_vector

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,

In [64]:
ytest_vector = le.transform(ytest)

In [65]:
ytest_vector

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1])